name: Build and Deploy to Droplet

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy app on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/speedrunstark
            git pull origin main
            pm2 stop speedrunstark
            yarn install
            cd packages/nextjs
            yarn build
            pm2 restart speedrunstark
            pm2 save